plugins { id 'java-library'; id 'net.neoforged.gradle.userdev' version '7.1.38' }
version=mod_version
group=mod_group_id
base { archivesName=mod_id }
java.toolchain.languageVersion=JavaLanguageVersion.of(21)
repositories { flatDir { dirs 'libs' } }
dependencies {
 implementation "net.neoforged:neoforge:${neo_version}"
 implementation files('libs/irons_spellbooks-1.21.1-3.16.3.jar')
 implementation files('libs/fantasy_armor-neoforge-1.2.4-1.21.1.jar')
}
tasks.withType(JavaCompile).configureEach { options.encoding='UTF-8' }
